'use client';
import {useMemo,useState} from 'react';
import JSZip from 'jszip';
import {ArrowLeft,ArrowRight,BookOpen,Check,ExternalLink,FileText,Grid2X2,MessageCircle,Package,ShieldCheck,Sparkles,Trash2,Upload,Volume2,X} from 'lucide-react';
type GridCount=4|6|8; type Action='message'|'compact'|'full'|'web'; type Voice='none'|'builtin'|'pack';
type Cell={label:string;action:Action;value:string};
const actionNames:Record<Action,string>={message:'跳出訊息',compact:'半頁 App',full:'全頁 App',web:'跳轉網頁'};
const labels=['開始檢測','我的報告','健康問答','今日任務','剩餘次數','我的積點','邀請好友','聯絡客服'];
const makeCells=(n:number):Cell[]=>Array.from({length:n},(_,i)=>({label:labels[i],action:i<2?'full':i===2?'message':i===7?'web':'compact',value:i===2?'健康問答':i===7?'https://example.com':`page-${i+1}`}));
const safe=(name:string)=>name.replace(/[^a-zA-Z0-9._\-\u4e00-\u9fff]/g,'-');
export default function Designer(){
 const [oa,setOa]=useState('看健健康顧問'),[project,setProject]=useState('facialmonitor'),[purpose,setPurpose]=useState('臉部健康檢測、報告查詢、每日任務與健康 AI 問答');
 const [count,setCount]=useState<GridCount>(6),[cells,setCells]=useState<Cell[]>(makeCells(6));
 const [fixed,setFixed]=useState(true),[rules,setRules]=useState('積點=你的目前積點\n次數=你目前剩餘的檢測次數\n真人=已為你暫停 AI 30 分鐘'),[ai,setAi]=useState(true),[voice,setVoice]=useState<Voice>('none'),[voiceName,setVoiceName]=useState('溫暖女聲');
 const [knowledge,setKnowledge]=useState(''),[tone,setTone]=useState('溫暖、清楚、簡短；不做醫療診斷，遇到急症請使用者立即就醫。'),[uploads,setUploads]=useState<File[]>([]);
 const [githubRepo,setGithubRepo]=useState(''),[supabaseRef,setSupabaseRef]=useState(''),[supabaseToken,setSupabaseToken]=useState(''),[lineSecret,setLineSecret]=useState(''),[lineToken,setLineToken]=useState(''),[aiApiKey,setAiApiKey]=useState(''),[liffCompact,setLiffCompact]=useState(''),[liffFull,setLiffFull]=useState('');
 const [book,setBook]=useState(false),[page,setPage]=useState(0),[demo,setDemo]=useState(false),[demoCell,setDemoCell]=useState<Cell|null>(null),[includeSecrets,setIncludeSecrets]=useState(false);
 const setGrid=(n:GridCount)=>{setCount(n);setCells(old=>Array.from({length:n},(_,i)=>old[i]||makeCells(n)[i]))};
 const update=(i:number,key:keyof Cell,value:string)=>setCells(c=>c.map((x,n)=>n===i?{...x,[key]:value}:x));
 const rawPrefix=project.trim().toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'')||'PROJECT';
 const prefix=/^[0-9]/.test(rawPrefix)?`PROJECT_${rawPrefix}`:rawPrefix;
 const config=useMemo(()=>({oaName:oa,projectName:project,appPurpose:purpose,richMenu:{grid:count,cells},replies:{fixed,items:rules.split('\n').filter(Boolean).map(x=>{const [keyword,...rest]=x.split('=');return{keyword:keyword?.trim(),reply:rest.join('=').trim()}})},ai:{enabled:ai,voice,voiceName:voice==='none'?'':voiceName,knowledgeFile:'ai/knowledge.md',toneFile:'ai/tone.md',uploads:uploads.map(f=>`ai/uploads/${safe(f.name)}`)},architecture:{website:'GitHub Pages',backend:'Supabase Edge Functions',line:'Messaging API + LINE Login/LIFF'}}),[oa,project,purpose,count,cells,fixed,rules,ai,voice,voiceName,uploads]);
 const chapters=useMemo(()=>[
  {title:'從零準備三個帳號',intro:'這本教學只保留必須由你親自登入、同意與複製的步驟。',steps:['準備可收驗證信的 Email 與手機。','開啟 GitHub，按 Sign up 建立帳號並完成 Email 驗證。','開啟 Supabase，按 Start your project；用 GitHub 登入並允許授權。','開啟 LINE Official Account Manager，以 LINE Business ID 登入；沒有帳號就先註冊。','建立一份私人筆記暫存稍後取得的 ID 與金鑰，請勿傳到公開聊天室。'],fields:[`${prefix}_GITHUB_REPOSITORY`,`${prefix}_SUPABASE_PROJECT_REF`,`${prefix}_LINE_OA_NAME`],link:'https://github.com/signup'},
  {title:`建立 GitHub 專案 ${project||'project'}`,intro:'GitHub 保存網頁程式；AI 稍後會替你建立檔案與發佈。',steps:[`登入 GitHub，右上角「＋」→ New repository。`,`Repository name 輸入「${project||'project'}」。`,'選擇 Private 或 Public，按 Create repository。','複製 repository 網址，回主頁貼到「連線資料單」。','在 ChatGPT/Codex 連接 GitHub；Claude Code 使用者則在電腦完成 gh auth login。'],fields:[`${prefix}_GITHUB_REPOSITORY`],link:'https://github.com/new'},
  {title:'建立 Supabase 帳號與 Project',intro:'Supabase 提供資料庫與接收 LINE 訊息的 Edge Function。',steps:['登入 Supabase Dashboard，按 New project；第一次使用先建立 Organization。',`Project name 輸入「${project||'project'}」，設定強密碼並選離客戶最近的 Region。`,'等待完成，進入 Project Settings → General；Reference ID 就是稍後 GitHub Secret 的 Project Ref 數值。','點右上角帳號 → Account Preferences → Access Tokens → Generate new token；產生的字串就是稍後 GitHub Secret 的 Access Token 數值。','立刻把兩個值記在私人筆記；Access Token 完成部署後可以撤銷。'],fields:[`${prefix}_SUPABASE_PROJECT_REF`,`${prefix}_SUPABASE_ACCESS_TOKEN`],link:'https://supabase.com/dashboard'},
  {title:'建立 LINE OA 與取得兩個 LINE 金鑰',intro:'先取得 Channel Secret 與 Channel Access Token，下一頁才有值可以填進 Supabase。',steps:[`在 LINE Official Account Manager 建立帳號，名稱填「${oa||'你的 LINE OA'}」。`,'帳號設定 → Messaging API → 啟用；建立或選擇一個 Provider，再按 LINE Developers 連結。',`在 Messaging API channel → Basic settings → Channel secret 按 Copy；這個值對應 ${prefix}_LINE_SECRET。`,`切到 Messaging API 分頁 → Channel access token → Issue；複製產生的長字串，對應 ${prefix}_LINE_TOKEN。`,'回 OA Manager → 回應設定，關閉 Greeting messages 與 Auto-reply messages，避免 webhook 回覆重複。'],fields:[`${prefix}_LINE_SECRET`,`${prefix}_LINE_TOKEN`],link:'https://manager.line.biz/'},
  {title:'取得 OpenAI 或 Claude API Key',intro:ai?'AI 回覆只需要選一家服務。ChatGPT／Claude 聊天訂閱不一定包含 API 用量，API 平台需另外啟用計費。':'目前未啟用 AI 回覆，這一頁可以略過。',steps:ai?['先選一家：使用 ChatGPT 模型選 OpenAI；使用 Claude 模型選 Anthropic。不要兩家都申請。','OpenAI：登入 platform.openai.com → 建立或選擇 Project → API keys → Create new secret key；複製只顯示一次的金鑰。','OpenAI：進入 Billing 加入付款方式／額度；ChatGPT Plus、Pro 或團隊訂閱不代表 API 帳戶已有可用額度。','Claude：登入 console.anthropic.com → Settings → API Keys → Create Key；複製只顯示一次的金鑰。','Claude：在 Console 的 Billing 啟用付款；Claude.ai 聊天訂閱與 Anthropic API Console 的計費可能分開。',`無論選哪一家，這串值都先記為 ${prefix}_AI_API_KEY；下一頁貼入 Supabase Edge Secrets。金鑰不可放入前端或 GitHub。`]:['回主頁保持「使用 AI 回覆」關閉。',`不需要建立 ${prefix}_AI_API_KEY，也不會產生 AI API 費用。`],fields:ai?[`${prefix}_AI_API_KEY`]:[],link:'https://platform.openai.com/api-keys'},
  {title:'把每一個金鑰放進 Supabase Edge Secrets',intro:'這些是 Edge Function 執行時需要的值；只放在伺服器端。',steps:[`進入 Supabase 專案 → Edge Functions → Secrets → Add new secret。`,`Key 填 ${prefix}_LINE_SECRET；Value 貼前面從 LINE Developers → Basic settings 複製的 Channel secret。`,`Key 填 ${prefix}_LINE_TOKEN；Value 貼前面從 LINE Developers → Messaging API 分頁 Issue 的 Channel access token。`,ai?`Key 填 ${prefix}_AI_API_KEY；Value 貼上一頁從 OpenAI Platform 或 Anthropic Console 建立的 API Key。`:`目前未啟用 AI，不需要建立 ${prefix}_AI_API_KEY。`,'逐項按 Save。不要把 Supabase Access Token 放在這裡；SUPABASE_URL 與系統金鑰由 Edge 執行環境預設提供。'],fields:[`${prefix}_LINE_SECRET`,`${prefix}_LINE_TOKEN`,...(ai?[`${prefix}_AI_API_KEY`]:[])],link:'https://supabase.com/dashboard/project/_/settings/functions'},
  {title:'設定 GitHub Actions Secrets',intro:'只有要讓 GitHub 推送後自動部署 Supabase 時才需要；若永遠由 AI 手動部署，可略過。',steps:['開啟你的 GitHub repository → Settings → Secrets and variables → Actions → New repository secret。',`Name 填 ${prefix}_SUPABASE_ACCESS_TOKEN；Secret 貼「Supabase 右上角帳號 → Account Preferences → Access Tokens」產生的 Personal Access Token。`,`再按 New repository secret；Name 填 ${prefix}_SUPABASE_PROJECT_REF；Secret 貼「Supabase Project Settings → General → Reference ID」。`,'兩筆存好後只會顯示名稱，不會再顯示完整值，這是正常的。','AI 產生的 workflow 必須引用這兩個完整的專案前綴名稱；LINE 與 AI 金鑰不需要放入 GitHub Actions。'],fields:[`${prefix}_SUPABASE_ACCESS_TOKEN`,`${prefix}_SUPABASE_PROJECT_REF`],link:'https://github.com/'},
  {title:'建立 LINE Login 與 LIFF',intro:'半頁與全頁 App 必須在和 Messaging API 相同的 Provider 下。',steps:['在 LINE Developers 的同一 Provider 按 Create a new channel → LINE Login。','完成名稱、Email、App type（Web app）與條款後建立 channel。','切到 LIFF 分頁，按 Add；有半頁格子就建立 Compact/Tall，有全頁格子就建立 Full。','Endpoint URL 先填有效 HTTPS 暫存網址；AI 發佈後再換正式網址。','複製 LIFF ID，回主頁填入對應欄位。'],fields:[`${prefix}_LIFF_ID_COMPACT`,`${prefix}_LIFF_ID_FULL`],link:'https://developers.line.biz/console/'},
  {title:'選擇安全封包方式',intro:'回到主頁填寫資料；所有內容只在瀏覽器裡組成 ZIP。',steps:['一般情況保持「安全模式」：ZIP 只有 .env.example，不含 Token 或 Secret。','把安全 ZIP 交給 AI 後，再依它的提示於本機工作區填寫 .env.local。','只有私有且受信任的 Codex／Claude Code 工作環境，才考慮開啟「高敏感模式」。','填寫 AI 知識與語氣，或上傳文件；先移除不必要的個資。','不要把 .env.local、Token、Secret 或高敏感 ZIP 上傳公開 GitHub或一般聊天室。'],fields:[`${prefix}_GITHUB_REPOSITORY`,`${prefix}_SUPABASE_PROJECT_REF`,`${prefix}_SUPABASE_ACCESS_TOKEN`,`${prefix}_LINE_SECRET`,`${prefix}_LINE_TOKEN`],link:'#connections'},
  {title:'把封包交給 ChatGPT/Codex 或 Claude Code',intro:'到這裡才由 AI 接手程式、資料庫、Edge Function、選單與部署。',steps:['建立新的程式工作任務，附上剛下載的 ZIP。','指示 AI：「解壓縮並完整執行 AGENT_PROMPT.md」。','只在受信任、可操作該 GitHub repository 的環境執行。','等待 AI 回傳 Web App URL、LINE Webhook URL 與 LIFF Endpoint URL。','AI 若要求重新貼出 Secret，先確認它是否已存在封包。'],fields:[`${prefix}_FINAL_APP_URL`,`${prefix}_FINAL_WEBHOOK_URL`],link:'https://chatgpt.com/'},
  {title:'最後只貼上 AI 回傳的 URL',intro:'程式工作已完成；你只做平台要求的最後人工確認。',steps:['LINE Developers → Messaging API → Webhook settings，貼上 AI 回傳的 Webhook URL。','按 Verify；成功後開啟 Use webhook。','LINE Login → LIFF，把正式 App URL 貼到每個 LIFF 的 Endpoint URL。','用手機加入 OA，逐格點擊並測試固定回覆、AI 回覆與語音。','全部正常後撤銷不再需要的 Supabase Access Token。'],fields:[`${prefix}_FINAL_WEBHOOK_URL`,`${prefix}_FINAL_APP_URL`],link:'https://developers.line.biz/console/'}
 ],[oa,project,prefix,ai]);
 async function zipFiles(){const zip=new JSZip();zip.file('project-config.json',JSON.stringify(config,null,2));zip.file('ai/knowledge.md',knowledge||'# AI 知識\n\n尚未提供額外知識。');zip.file('ai/tone.md',tone||'# 回覆語氣\n\n自然、清楚、簡短。');for(const file of uploads)zip.file(`ai/uploads/${safe(file.name)}`,file);const env:{[key:string]:string}={[`${prefix}_GITHUB_REPOSITORY`]:githubRepo,[`${prefix}_SUPABASE_PROJECT_REF`]:supabaseRef,[`${prefix}_SUPABASE_ACCESS_TOKEN`]:supabaseToken,[`${prefix}_LINE_SECRET`]:lineSecret,[`${prefix}_LINE_TOKEN`]:lineToken,[`${prefix}_AI_API_KEY`]:aiApiKey,[`${prefix}_LIFF_ID_COMPACT`]:liffCompact,[`${prefix}_LIFF_ID_FULL`]:liffFull};zip.file('.env.example',Object.keys(env).map(k=>`${k}=`).join('\n')+'\n');if(includeSecrets)zip.file('.env.local',Object.entries(env).map(([k,v])=>`${k}=${v}`).join('\n')+'\n');zip.file('richmenu-config.json',JSON.stringify({grid:count,cells:cells.map((c,i)=>({id:i+1,...c}))},null,2));zip.file('fixed-replies.json',JSON.stringify(config.replies,null,2));zip.file('AGENT_PROMPT.md',`# AI 執行任務：${project}\n\n先讀取所有 JSON、ai/knowledge.md、ai/tone.md、ai/uploads/。${includeSecrets?'在受信任的私有工作環境中安全讀取 .env.local，絕不可輸出或提交 secret。':'此安全封包不含 Secret。使用者已依教學把執行期金鑰放入 Supabase Edge Secrets，並可選擇把部署憑證放入 GitHub Actions Secrets；不可要求使用者在公開對話貼出憑證。'}\n\n請完成網頁 App、${count} 格 LINE 圖文選單、Supabase schema/RLS 與 Edge Functions、LINE webhook、固定回覆、AI ${voice==='none'?'文字':`文字與${voiceName}語音`}，推送 GitHub、部署並測試。GitHub workflow 必須引用帶有 ${prefix}_ 前綴的 repository secrets，不要把任何值寫進程式或 workflow。\n\n最後只回傳：正式 Web App URL、LINE Webhook URL、各 LIFF Endpoint URL，以及使用者要貼入 LINE Developers 的位置。若憑證缺漏才提問。\n`);zip.file('SECRETS-MAP.md',`# Secret 放置對照\n\n## Supabase Edge Secrets（程式執行時）\n- ${prefix}_LINE_SECRET\n- ${prefix}_LINE_TOKEN\n- ${prefix}_AI_API_KEY（啟用 AI 時）\n\n## GitHub Actions Secrets（自動部署時）\n- ${prefix}_SUPABASE_ACCESS_TOKEN\n- ${prefix}_SUPABASE_PROJECT_REF\n\n不要把任何 Secret 寫入前端、GitHub 程式碼或 workflow。\n`);zip.file('SECURITY.md',includeSecrets?'# 高敏感封包\n\n本封包含 .env.local。只可交給受信任的私有 AI 工作環境，不可上傳一般聊天室、雲端分享或 GitHub。部署完成後刪除封包並撤銷暫時 Access Token。\n':'# 安全封包\n\n本封包不含 Secret。正式金鑰應依 SECRETS-MAP.md 放入 Supabase Edge Secrets 與 GitHub Actions Secrets。\n');const blob=await zip.generateAsync({type:'blob'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`${project||'line-oa'}-${includeSecrets?'trusted-private':'safe'}-ai-package.zip`;a.click();URL.revokeObjectURL(u)}
 return <main className="designer"><header className="designer-top"><a href="#home"><span><MessageCircle size={19}/></span>LINE OA KIT</a><div><ShieldCheck size={15}/> 資料只在本機組成封包</div></header>
 <section id="home" className="designer-hero"><div><small><Sparkles size={13}/> FACIALMONITOR EXPERIENCE BUILDER</small><h1>你完成帳號連線，<em>AI 完成其餘建置。</em></h1><p>先選介面與回覆方式，再照翻頁教學完成 GitHub、Supabase、LINE OA。最後把封包交給 AI，只需貼上它回傳的網址。</p></div><div className="mini-menu"><b>{oa||'你的 LINE OA'}</b><div className={`mini-grid g${count}`}>{cells.map((c,i)=><span key={i}>{c.label||i+1}<small>{actionNames[c.action]}</small></span>)}</div></div></section>
 <section className="wizard"><Title n="01" title="先命名，再決定 App 做什麼" note="欄位前綴會自動使用專案名稱。"/><div className="names"><label>LINE OA 名稱<input value={oa} onChange={e=>setOa(e.target.value)}/></label><label>專案名稱<input value={project} onChange={e=>setProject(e.target.value.replace(/\s+/g,'-').toLowerCase())}/><small className="prefix-preview">欄位前綴：{prefix}_</small></label></div><label>網頁 App 要做什麼？<textarea value={purpose} onChange={e=>setPurpose(e.target.value)}/></label></section>
 <section className="wizard"><Title n="02" title="選擇 4、6 或 8 格介面" note="每一格可跳訊息、半頁 App、全頁 App或網頁。"/><div className="grid-picker">{([4,6,8] as GridCount[]).map(n=><button className={count===n?'active':''} onClick={()=>setGrid(n)} key={n}><Grid2X2 size={18}/><b>{n} 格</b><small>{n===4?'精簡主功能':n===6?'標準服務選單':'完整功能中心'}</small>{count===n&&<Check size={16}/>}</button>)}</div><div className="cell-editor">{cells.map((c,i)=><article key={i}><div className="cell-no">{String(i+1).padStart(2,'0')}</div><label>格子名稱<input value={c.label} onChange={e=>update(i,'label',e.target.value)}/></label><label>點擊後<select value={c.action} onChange={e=>update(i,'action',e.target.value as Action)}><option value="message">跳出訊息</option><option value="compact">半頁 App</option><option value="full">全頁 App</option><option value="web">跳轉網頁</option></select></label><label>{c.action==='message'?'送出的文字':c.action==='web'?'https 網址':'App 頁面代號'}<input value={c.value} onChange={e=>update(i,'value',e.target.value)}/></label></article>)}</div></section>
 <section className="wizard"><Title n="03" title="設定固定回覆與 AI 素材" note="可直接填寫，也可把知識與語氣文件一起放入封包。"/><Toggle checked={fixed} onChange={setFixed} title="使用固定回覆訊息" note="完全命中時不呼叫 AI"/>{fixed&&<label className="rule-box">每行一組「關鍵字=回覆內容」<textarea value={rules} onChange={e=>setRules(e.target.value)}/></label>}<Toggle checked={ai} onChange={setAi} title="使用 AI 回覆" note="處理自由問句與連續對話"/>{ai&&<div className="ai-materials"><label>AI 應知道的知識<textarea value={knowledge} onChange={e=>setKnowledge(e.target.value)} placeholder="品牌、產品、FAQ、限制、服務流程…"/></label><label>AI 回覆語氣與禁忌<textarea value={tone} onChange={e=>setTone(e.target.value)}/></label><label className="upload-box"><Upload size={20}/><b>上傳 AI 知識／語氣文件</b><small>TXT、MD、JSON、CSV、PDF、DOC、DOCX；每檔最多 10MB</small><input type="file" multiple accept=".txt,.md,.json,.csv,.pdf,.doc,.docx" onChange={e=>setUploads(old=>[...old,...Array.from(e.target.files||[]).filter(f=>f.size<=10*1024*1024)])}/></label>{uploads.length>0&&<div className="file-list">{uploads.map((f,i)=><div key={`${f.name}-${i}`}><span>{f.name}<small>{(f.size/1024).toFixed(0)} KB</small></span><button onClick={()=>setUploads(x=>x.filter((_,n)=>n!==i))}><Trash2 size={15}/></button></div>)}</div>}<div className="voice-box"><h3><Volume2 size={18}/> AI 要不要語音回覆？</h3><div>{([['none','只用文字'],['builtin','使用內建語音'],['pack','使用自訂語音包']] as [Voice,string][]).map(([v,t])=><button className={voice===v?'active':''} onClick={()=>setVoice(v)} key={v}>{t}</button>)}</div>{voice!=='none'&&<label>語音／聲線名稱<input value={voiceName} onChange={e=>setVoiceName(e.target.value)}/></label>}</div></div>}</section>
 <section id="connections" className="wizard"><Title n="04" title="完成教學後，回來填連線資料" note="預設下載不含 Secret；資料不會傳到本站伺服器。"/><div className="connection-grid"><label>GitHub Repository URL<input value={githubRepo} onChange={e=>setGithubRepo(e.target.value)} placeholder="https://github.com/帳號/專案"/></label><label>Supabase Project Reference ID<input value={supabaseRef} onChange={e=>setSupabaseRef(e.target.value)}/></label><label>Supabase Access Token<input type="password" value={supabaseToken} onChange={e=>setSupabaseToken(e.target.value)}/></label><label>LINE Channel Secret<input type="password" value={lineSecret} onChange={e=>setLineSecret(e.target.value)}/></label><label>LINE Channel Access Token<input type="password" value={lineToken} onChange={e=>setLineToken(e.target.value)}/></label>{ai&&<label>AI API Key<input type="password" value={aiApiKey} onChange={e=>setAiApiKey(e.target.value)} placeholder="OpenAI／Anthropic 等服務金鑰"/></label>}<label>LIFF ID（半頁）<input value={liffCompact} onChange={e=>setLiffCompact(e.target.value)}/></label><label>LIFF ID（全頁）<input value={liffFull} onChange={e=>setLiffFull(e.target.value)}/></label></div><div className="secret-map"><b>金鑰應放的位置</b><span><strong>Supabase Edge Secrets</strong>：{prefix}_LINE_SECRET、{prefix}_LINE_TOKEN{ai?`、${prefix}_AI_API_KEY`:''}</span><span><strong>GitHub Actions Secrets</strong>：{prefix}_SUPABASE_ACCESS_TOKEN、{prefix}_SUPABASE_PROJECT_REF（僅自動部署需要）</span></div><button className={`secret-choice ${includeSecrets?'danger':''}`} onClick={()=>setIncludeSecrets(v=>!v)}><span className="toggle"><i/></span><div><b>{includeSecrets?'高敏感模式：ZIP 將包含 .env.local':'安全模式：ZIP 不包含 Secret（建議）'}</b><small>{includeSecrets?'只可交給受信任的私有 Codex／Claude Code 工作環境':'先依教學把金鑰放入 Edge Secrets／Actions Secrets，再把安全封包交給 AI'}</small></div></button><p className="secret-note">一般 ChatGPT／Claude 網頁對話可能會保存附件；請使用安全模式。只有在你確認工作環境私有、受信任且不會保留附件時，才開啟高敏感模式。</p></section>
 <section className="generate"><div><small>HUMAN FIRST, AI NEXT</small><h2>先讀零起點教學，再下載 AI 封包</h2><p>{oa} · {project} · {count} 格 · {uploads.length} 個附件 · {includeSecrets?'含 Secret':'安全模式'}</p></div><button onClick={()=>{setPage(0);setBook(true)}}><BookOpen size={19}/> 開始翻頁教學</button><button className="zip" onClick={zipFiles}><Package size={19}/> 下載 AI 執行封包</button></section>
 <section className="demo-callout"><div><small>INTERACTIVE PREVIEW</small><h2>先看看使用者點擊後會發生什麼</h2><p>依照目前的 {count} 格設定，模擬訊息、半頁 App、全頁 App與外部網頁。</p></div><button onClick={()=>{setDemoCell(null);setDemo(true)}}><MessageCircle size={19}/> 開啟 LINE OA 示意畫面</button></section>
 {book&&<div className="book-backdrop"><div className="book"><button className="book-close" onClick={()=>setBook(false)}><X/></button><div className="book-progress"><span style={{width:`${((page+1)/chapters.length)*100}%`}}/></div><div key={page} className="book-page"><small className="page-tag">{String(page+1).padStart(2,'0')} / {String(chapters.length).padStart(2,'0')} · 僅限使用者操作</small><h2>{chapters[page].title}</h2><p className="book-intro">{chapters[page].intro}</p><ol>{chapters[page].steps.map((s,i)=><li key={s}><b>{i+1}</b><span>{s}</span></li>)}</ol><div className="field-sheet"><h3><FileText size={16}/> 這一頁會取得／填寫的欄位</h3>{chapters[page].fields.map(x=><code key={x}>{x}</code>)}</div><div className="book-tools"><a href={chapters[page].link} target={chapters[page].link.startsWith('#')?'_self':'_blank'}>開啟對應頁面 <ExternalLink size={13}/></a><small>本教學不包含 AI 可以代做的程式步驟</small></div></div><div className="book-nav"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}><ArrowLeft/> 上一頁</button><span>{page+1} / {chapters.length}</span>{page<chapters.length-1?<button onClick={()=>setPage(p=>p+1)}>下一頁 <ArrowRight/></button>:<button className="finish" onClick={()=>setBook(false)}><Check/> 教學完成</button>}</div></div></div>}
 {demo&&<div className="demo-backdrop"><div className="demo-stage"><button className="demo-close" onClick={()=>setDemo(false)}><X/></button><div className="phone"><div className="line-head"><ArrowLeft size={18}/><b>{oa||'你的 LINE OA'}</b><span>☰</span></div><div className="chat-area"><div className="oa-avatar">OA</div><div className="welcome">歡迎加入 {oa||'你的 LINE OA'}！<br/>請點選下方服務。</div>{demoCell?.action==='message'&&<div className="user-message">{demoCell.value||demoCell.label}</div>}{demoCell?.action==='web'&&<div className="web-notice"><ExternalLink size={18}/><b>將開啟外部網頁</b><span>{demoCell.value||'尚未填寫網址'}</span></div>}</div><div className={`demo-rich g${count}`}>{cells.map((c,i)=><button key={i} className={demoCell===c?'active':''} onClick={()=>setDemoCell(c)}><b>{c.label}</b><small>{actionNames[c.action]}</small></button>)}</div>{demoCell&&(demoCell.action==='compact'||demoCell.action==='full')&&<div className={`app-preview ${demoCell.action}`}><div className="app-bar"><b>{demoCell.label}</b><button onClick={()=>setDemoCell(null)}><X size={16}/></button></div><div className="app-copy"><span>APP 畫面</span><h3>{demoCell.label}</h3><p>{demoCell.action==='compact'?'這是從 LINE 下方彈出的半頁 App。':'這是覆蓋聊天畫面的全頁 App。'}</p><button>示意操作按鈕</button></div></div>}</div><aside><small>LIVE REACTION</small><h2>{demoCell?demoCell.label:'點一格開始體驗'}</h2><p>{demoCell?`${actionNames[demoCell.action]}：${demoCell.value||'尚未填內容'}`:'右側手機會依每一格設定呈現不同反應。'}</p><div className="legend"><span>訊息：出現在聊天室</span><span>半頁：由底部彈出</span><span>全頁：覆蓋聊天畫面</span><span>網頁：顯示外部跳轉</span></div></aside></div></div>}
 <footer>LINE OA KIT · based on FACIALMONITOR deployment experience</footer></main>}
function Title({n,title,note}:{n:string;title:string;note:string}){return <div className="wizard-title"><span>{n}</span><div><h2>{title}</h2><p>{note}</p></div></div>}
function Toggle({checked,onChange,title,note}:{checked:boolean;onChange:(v:boolean)=>void;title:string;note:string}){return <button className={`toggle-card ${checked?'on':''}`} onClick={()=>onChange(!checked)}><span className="toggle"><i/></span><div><b>{title}</b><small>{note}</small></div></button>}
